/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.*;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author keslerth
 */
public class vPrincipal extends javax.swing.JFrame {
    public static Restaurante restaurante;
    
    ArrayList direccion;
    String path;  
    URL url;
    ImageIcon foto;
    
    infoRest vInfoRes;
    public static AtenderCliente vAtenderCliente;
    AgregarCliente vAgregarCliente;
    EscogerMesa vEscogerMesa;
    PedirComida vPedirComida;
    ArrayList<Mesero> meseros;
    ArrayList<Cocinero> cocineros;
    ArrayList<Cliente> clientes;
    
    /**
     * Creates new form vPrincipal
     */
    public vPrincipal() {
        initComponents();
        meseros=new ArrayList<Mesero>();
        cocineros=new ArrayList<Cocinero>();
        clientes=new ArrayList<Cliente>();
        //Direccion------
        direccion = new ArrayList();
        direccion.add("Alajuela");
        direccion.add("San Carlos");
        direccion.add("Quesada");
        direccion.add("300m liceo SC");
        //Direccion-------
        //Foto---
        path = "/images/queso.png";
        url = this.getClass().getResource(path);
        foto = new ImageIcon(url);
        //Foto---
        //Mesero---
        String idiomasM1="";
        Mesero mesero1 = new Mesero(idiomasM1, "Josefina", 123, 88888888, "Por San Jose", "fina@gg.com");
        //Mesero---
        Mesa mesa1 = new Mesa(1, 5, true);
        Mesa mesa2 = new Mesa(2, 2, true);
        Mesa mesa3 = new Mesa(3, 7, true);
        
        ArrayList<Plato> platos = new ArrayList();
        ArrayList<Bebida> bebidas = new ArrayList();
        
        Menu menu = new Menu(platos,bebidas);
        ArrayList ingredientesP1 = new ArrayList();
        ArrayList ingredientesP2 = new ArrayList();
        
        Plato plato1 = new Plato(1, "Arroz", ingredientesP1, 200, 300, "Bueno", null);
        Plato plato2 = new Plato(1, "Bisec", ingredientesP2, 200, 300, "Recien hecha", null);
        Bebida bebida1 = new Bebida("Coca Cola", 500, 350);
        Bebida bebida2 = new Bebida("Agua con hielo", 0, 350);
        Bebida bebida3 = new Bebida("Te frío", 500, 600);
        
        menu.agregarPlato(plato1);
        menu.agregarPlato(plato2);
        menu.agregarBebida(bebida1);
        menu.agregarBebida(bebida2);
        menu.agregarBebida(bebida3);
        
        ArrayList<Mesero> meseros = new ArrayList();
        ArrayList<Mesa> mesas = new ArrayList();
        ArrayList<Menu> menus = new ArrayList();
        meseros.add(mesero1);
        mesas.add(mesa1);
        mesas.add(mesa2);
        mesas.add(mesa3);
        menus.add(menu);
        
        restaurante = new Restaurante("Cheese Restaurante", foto, 86360027, direccion, "cheeseres@gmail.com", null, meseros, null, null, mesas, menus);
        //Inicializar ventanas
        vInfoRes = new infoRest(restaurante);
        vAtenderCliente = new AtenderCliente(restaurante,vAgregarCliente,vEscogerMesa,vPedirComida);
        vAgregarCliente = new AgregarCliente(restaurante, vAtenderCliente);
        vEscogerMesa = new EscogerMesa(restaurante, vAtenderCliente);
        vPedirComida = new PedirComida(restaurante);
        //Agregar ventanas al Escritorio
        vAtenderCliente = new AtenderCliente(restaurante,vAgregarCliente,vEscogerMesa,vPedirComida);
        this.jDesktopPane1.add(vAtenderCliente);
        this.jDesktopPane1.add(vInfoRes);
        this.jDesktopPane1.add(vAgregarCliente);
        this.jDesktopPane1.add(vEscogerMesa);
        this.jDesktopPane1.add(vPedirComida);
        this.jDesktopPane1.add(new AgregarEmpleado());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        lblNomMesero = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuRes = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuMes = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuCoc = new javax.swing.JMenu();
        jMenuCli = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNomMesero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNomMesero.setForeground(new java.awt.Color(255, 255, 255));
        lblNomMesero.setText("Mesero");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(533, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(463, Short.MAX_VALUE)
                .addComponent(lblNomMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPane1.setLayer(lblNomMesero, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenuRes.setText("Restaurante");

        jMenuItem1.setText("Info");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuRes.add(jMenuItem1);

        jMenuItem4.setText("Atender");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuRes.add(jMenuItem4);

        jMenuItem2.setText("Factura");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuRes.add(jMenuItem2);

        jMenuItem5.setText("Empleados");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuRes.add(jMenuItem5);

        jMenuBar1.add(jMenuRes);

        jMenuMes.setText("Mesero");

        jMenuItem3.setText("Ver mesas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuMes.add(jMenuItem3);

        jMenuBar1.add(jMenuMes);

        jMenuCoc.setText("Cocinero");
        jMenuBar1.add(jMenuCoc);

        jMenuCli.setText("Cliente");
        jMenuBar1.add(jMenuCli);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        vInfoRes.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        int mesero = Integer.parseInt(JOptionPane.showInputDialog(null, "Introduzca la cedula, mesero"));
        for(int i = 0;i<restaurante.getMeseros().size();i++){
            if(restaurante.getMeseros().get(i).getCedula() == mesero){
                vAtenderCliente = new AtenderCliente(restaurante,vAgregarCliente,vEscogerMesa,vPedirComida);
                this.jDesktopPane1.add(vAtenderCliente);
                vAtenderCliente.show();
                vAtenderCliente.orden.setMeseroAtiende(restaurante.getMeseros().get(i));
                this.lblNomMesero.setText(restaurante.getMeseros().get(i).getNombreFull());
            }
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCli;
    private javax.swing.JMenu jMenuCoc;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenu jMenuMes;
    private javax.swing.JMenu jMenuRes;
    private javax.swing.JLabel lblNomMesero;
    // End of variables declaration//GEN-END:variables
}
